# GitHub workflow for deploying the documentation to GitHub Pages
name: deploy_doc

on:
    push:
        branches:
          - master
        paths:
          - 'doc/**'

jobs:
    deploy_doc:
        runs-on: ubuntu-22.04
        steps:
          - name: üõéÔ∏è Checkout
            uses: actions/checkout@v4
          - name: üêã Clean dangling Docker containers
            uses: ./.github/actions/docker-clean
          - name: üìù Set Docker username
            env:
                docker_username: ${{ secrets.DOCKER_USERNAME }}
            run: |
                [ -n "${docker_username}" ] || docker_username=jmddk
                echo "docker_username=${docker_username}" >> "${GITHUB_ENV}"
          - name: üêã Pull Docker image
            run: docker pull ${docker_username}/concept:latest
          - name: üìñ Build documentation
            run: |
                sleep 1
                docker run \
                    -v "${GITHUB_WORKSPACE}":/github \
                    --name "${GITHUB_REPOSITORY//\//_}__${GITHUB_WORKFLOW}__${GITHUB_JOB}__$(date +%s)" \
                    --rm \
                    ${docker_username}/concept:latest \
                    bash -O extglob -c ': \
                        && source ~/.bashrc \
                        && rm -rf "${concept_dir}/"!(dep) \
                        && cp -r /github/!(dep) "${concept_dir}/" \
                        && (cd "${concept_dir}" && make clean-doc && make doc) \
                        && sudo su -c "rm -rf /github/publish" \
                        && sudo su -c "cp -r \"${doc_dir}/publish\" /github/" \
                        && sudo su -c "chmod -R a+rwX /github/publish" \
                    '
          - name: üöÄ Deploy documentation
            uses: peaceiris/actions-gh-pages@v3
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: publish

