# GitHub workflow for testing the update utility
name: test_update

on:
    pull_request:
        branches:
          - master

jobs:
    test_update:
        runs-on:
          group: private
          labels: [self-hosted, ubuntu-22.04]
        steps:
          - name: üõéÔ∏è Checkout
            uses: actions/checkout@v3
          - name: üêã Clean dangling Docker containers
            uses: ./.github/actions/docker-clean
          - name: üìù Set Docker username
            env:
                docker_username: ${{ secrets.DOCKER_USERNAME }}
            run: |
                [ -n "${docker_username}" ] || docker_username=jmddk
                echo "docker_username=${docker_username}" >> "${GITHUB_ENV}"
          - name: üêã Pull Docker image
            run: docker pull ${docker_username}/concept:latest
          - name: ü§ñ Test update utility
            run: |
                sleep 1
                docker run \
                    -e make_jobs="-j 1" \
                    -v "${GITHUB_WORKSPACE}":/github \
                    --name "${GITHUB_REPOSITORY//\//_}__${GITHUB_WORKFLOW}__${GITHUB_JOB}__$(date +%s)" \
                    --rm \
                    ${docker_username}/concept:latest \
                    bash -O extglob -c ': \
                        && source ~/.bashrc \
                        && rm -rf "${concept_dir}/"!(dep) \
                        && cp -r /github/!(dep) "${concept_dir}/" \
                        && concept -u update current -y \
                        && concept -u update current -y --class \
                        && concept -t concept_vs_class_pm \
                    '

